


#include <e-data-book-types.h>
#include "e-data-book-enumtypes.h"

/* enumerations from "e-data-book-types.h" */
GType
e_data_book_status_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { E_DATA_BOOK_STATUS_SUCCESS, "E_DATA_BOOK_STATUS_SUCCESS", "success" },
      { E_DATA_BOOK_STATUS_BUSY, "E_DATA_BOOK_STATUS_BUSY", "busy" },
      { E_DATA_BOOK_STATUS_REPOSITORY_OFFLINE, "E_DATA_BOOK_STATUS_REPOSITORY_OFFLINE", "repository-offline" },
      { E_DATA_BOOK_STATUS_PERMISSION_DENIED, "E_DATA_BOOK_STATUS_PERMISSION_DENIED", "permission-denied" },
      { E_DATA_BOOK_STATUS_CONTACT_NOT_FOUND, "E_DATA_BOOK_STATUS_CONTACT_NOT_FOUND", "contact-not-found" },
      { E_DATA_BOOK_STATUS_CONTACTID_ALREADY_EXISTS, "E_DATA_BOOK_STATUS_CONTACTID_ALREADY_EXISTS", "contactid-already-exists" },
      { E_DATA_BOOK_STATUS_AUTHENTICATION_FAILED, "E_DATA_BOOK_STATUS_AUTHENTICATION_FAILED", "authentication-failed" },
      { E_DATA_BOOK_STATUS_AUTHENTICATION_REQUIRED, "E_DATA_BOOK_STATUS_AUTHENTICATION_REQUIRED", "authentication-required" },
      { E_DATA_BOOK_STATUS_UNSUPPORTED_FIELD, "E_DATA_BOOK_STATUS_UNSUPPORTED_FIELD", "unsupported-field" },
      { E_DATA_BOOK_STATUS_UNSUPPORTED_AUTHENTICATION_METHOD, "E_DATA_BOOK_STATUS_UNSUPPORTED_AUTHENTICATION_METHOD", "unsupported-authentication-method" },
      { E_DATA_BOOK_STATUS_TLS_NOT_AVAILABLE, "E_DATA_BOOK_STATUS_TLS_NOT_AVAILABLE", "tls-not-available" },
      { E_DATA_BOOK_STATUS_NO_SUCH_BOOK, "E_DATA_BOOK_STATUS_NO_SUCH_BOOK", "no-such-book" },
      { E_DATA_BOOK_STATUS_BOOK_REMOVED, "E_DATA_BOOK_STATUS_BOOK_REMOVED", "book-removed" },
      { E_DATA_BOOK_STATUS_OFFLINE_UNAVAILABLE, "E_DATA_BOOK_STATUS_OFFLINE_UNAVAILABLE", "offline-unavailable" },
      { E_DATA_BOOK_STATUS_SEARCH_SIZE_LIMIT_EXCEEDED, "E_DATA_BOOK_STATUS_SEARCH_SIZE_LIMIT_EXCEEDED", "search-size-limit-exceeded" },
      { E_DATA_BOOK_STATUS_SEARCH_TIME_LIMIT_EXCEEDED, "E_DATA_BOOK_STATUS_SEARCH_TIME_LIMIT_EXCEEDED", "search-time-limit-exceeded" },
      { E_DATA_BOOK_STATUS_INVALID_QUERY, "E_DATA_BOOK_STATUS_INVALID_QUERY", "invalid-query" },
      { E_DATA_BOOK_STATUS_QUERY_REFUSED, "E_DATA_BOOK_STATUS_QUERY_REFUSED", "query-refused" },
      { E_DATA_BOOK_STATUS_COULD_NOT_CANCEL, "E_DATA_BOOK_STATUS_COULD_NOT_CANCEL", "could-not-cancel" },
      { E_DATA_BOOK_STATUS_OTHER_ERROR, "E_DATA_BOOK_STATUS_OTHER_ERROR", "other-error" },
      { E_DATA_BOOK_STATUS_INVALID_SERVER_VERSION, "E_DATA_BOOK_STATUS_INVALID_SERVER_VERSION", "invalid-server-version" },
      { E_DATA_BOOK_STATUS_NO_SPACE, "E_DATA_BOOK_STATUS_NO_SPACE", "no-space" },
      { E_DATA_BOOK_STATUS_INVALID_ARG, "E_DATA_BOOK_STATUS_INVALID_ARG", "invalid-arg" },
      { E_DATA_BOOK_STATUS_NOT_SUPPORTED, "E_DATA_BOOK_STATUS_NOT_SUPPORTED", "not-supported" },
      { E_DATA_BOOK_STATUS_NOT_OPENED, "E_DATA_BOOK_STATUS_NOT_OPENED", "not-opened" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static ("EDataBookStatus", values);
  }
  return etype;
}



